create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

drop policy if exists "Allow anonymous inserts" on public.contact_submissions;
create policy "Allow anonymous inserts"
on public.contact_submissions
for insert
to anon
with check (true);

drop policy if exists "Allow authenticated read access" on public.contact_submissions;
create policy "Allow authenticated read access"
on public.contact_submissions
for select
to authenticated
using (true);
